### ISSUE TITLE
rqt_robot_monitor: Apparent threading bug

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_robot_monitor#1]
_From @abencz on December 11, 2014 18:35_

While running rqt_robot_monitor I get a continuous stream of the following in the parent terminal:

```
Traceback (most recent call last):
  File "/home/alex/ros_rocksteady_gui/src/rqt_robot_plugins/rqt_robot_monitor/src/rqt_robot_monitor/timeline_view.py", line 194, in _slot_redraw
    for i, m in enumerate(self._timeline):
  File "/home/alex/ros_rocksteady_gui/src/rqt_robot_plugins/rqt_robot_monitor/src/rqt_robot_monitor/timeline.p  y", line 158, in __iter__
    for msg in self._queue:
RuntimeError: deque mutated during iteration
```

Looks like the timeline queue is being modified by the ROS message callback in the `Timeline` class while at the same time being iterated over by `TimelineView`. I'm not what a good fix is, but I'm guessing this is causing more than just annoying error messages because I also see frequent rqt_robot_monitor freezes and crashes - most often when using the inspector window.

_Copied from original issue: ros-visualization/rqt_robot_plugins#78_

**Comment by dirk-thomas** [comment]
_From @ablasdel on December 15, 2014 6:57_

Yes it looks like the issue is that a message is coming in while screen is being redrawn. Since a message coming in triggers a redraw if the messages get pumped out fast enough this is going to happen often.

I think the solution to this is to cache all incoming messages in the callback and them process them at a regular rate. This way the redraw rate is fairly fixed. User interaction will generate redraws also so to be extra safe it would be wise to mutex the redraw and "cache process" code.

I probably won't be able to code this up until next year unfortunately.

**Comment by dirk-thomas** [comment]
_From @abencz on December 15, 2014 21:23_

I'm going to take a crack at fixing it.

**Comment by dirk-thomas** [comment]
_From @ablasdel on December 15, 2014 22:46_

Awesome! Looking forward to a PR!

**Comment by dirk-thomas** [comment]
_From @ablasdel on January 7, 2015 23:44_

@abencz any updates?

**Comment by dirk-thomas** [comment]
_From @abencz on January 9, 2015 19:4_

Didn't get a chance to look at this before Christmas vacation. Will be looking at it next week.

**Comment by dirk-thomas** [comment]
_From @ablasdel on January 9, 2015 19:6_

No problem was just doing a check on all issue status. Thanks for looking into it!

**Comment by arne48** [comment]
The described condition is fixed now.

**Comment by dirk-thomas** [comment]
I just noticed that you tagged a new release (0.5.8) :+1: You will still need to release this new version into the various ROS distros using `bloom` to make them available to users.

**Comment by arne48** [comment]
@dirk-thomas Thank you for giving me hints that is really helpful because I am quite new to the whole ROS distribution system. I actually watched your presentation from last year's ROSCon about the build farm and it took some time to read through everything. Since this was my first release I tried to be careful to not breaking things. But everything worked out well now. Using bloom makes everything really easy :)
BTW: could you add me please as a collaborator for the rqt_moveit package so I can maintain that by myself as well?

**Comment by dirk-thomas** [comment]
:+1:

I added you as an admin collaborator to `rqt_moveit` as well as its release repo.
