### ISSUE TITLE
Loading standalone broken? Blank window

### ISSUE THREAD

**Issue by agutenkunst** [ros-visualization/rqt_robot_monitor#12]
I am using melodic/Ubuntu 18.04 and while I can use the Plugin in the rqt_gui 
`rqt -s rqt_robot_monitor.robot_monitor_plugin.RobotMonitorPlugin` or `rosrun rqt_robot_monitor rqt_robot_monitor` fails.

It just displays a blank window:

![Screenshot from 2019-07-11 13-25-36](https://user-images.githubusercontent.com/29709121/61047272-6770f000-a3df-11e9-8182-95c3cf260f16.png)

Other plugins such as `rqt -s rqt_console.console.Console` work.

**Comment by arne48** [comment]
Sorry for the long delay.
Because I couldn't reproduce this behavior, would you please record a rosbag I can use as a reference to figure out what the problem is?
Thank you very much.

**Comment by arne48** [comment]
Sorry for the long delay.
I tried to recreate this behavior but I couldn't.
Could you please provide a description how you provoke this problem on your device?

**Comment by arne48** [comment]
Could you please try out master or 0.5.9 from this repo and tell me if the issue is still present?

**Comment by agutenkunst** [comment]
Sorry for the late reply. Works on 0.5.9. Maybe it was something on my side. Closing.

**Comment by edgariph98** [comment]
Does anyone know how to properly address the issue, I am having the same problem?

**Comment by arne48** [comment]
@edgariph98 thank you for reporting this issue.
Could you please give me a few more details so that I can try to reproduce the issue you have?
