### ISSUE TITLE
New rqt_robot_monitor release to Focal?

### ISSUE THREAD

**Issue by sloretz** [ros-visualization/rqt_robot_monitor#20]
Mind making a new release with 4596ce66ed3176d911946f74ae28d705d5bbe910 into focal? It looks like `ros-noetic-rqt-robot-monitor` is uninstallable at the moment because of the python 2 dependency

```
executing command [apt-get install -y ros-noetic-rqt-robot-monitor]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-noetic-rqt-robot-monitor : Depends: python-rospkg but it is not installable
E: Unable to correct problems, you have held broken packages
```

**Comment by arne48** [comment]
thanks for pointing this out @sloretz 
I will make a new release today.

BTW. Do you know whom to ask to get ros2 gbp release repositories for the packages we ported?
I read a pinned post on discourse by tfoote [link](https://discourse.ros.org/t/guidelines-for-asking-for-new-package-releases/618) to open an issue. Is this still the recommended process?
Thanks in advance for your help.

**Comment by sloretz** [comment]
> Do you know whom to ask to get ros2 gbp release repositories for the packages we ported?
I read a pinned post on discourse by tfoote link to open an issue in the package repository. Is this still the recommended process for migrations to ros2?

I'm not sure I understand the question. Are you saying you've ported some packages to ROS 2, and would like a release repo created in the https://github.com/ros2-gbp/ org for it? If so, I'm not sure what the process is. I think posting an issue in the package repository is the right thing in case the maintainer has started that, but I also I think you could ask on [the Packaging and Release Management discourse category](https://discourse.ros.org/c/release/16) for someone to create the repo and give you write access to it.


I'll close this issue since https://github.com/ros/rosdistro/pull/24854 was made :rocket:
