### ISSUE TITLE
[ros2] toplevel status is not displayed correctly

### ISSUE THREAD

**Issue by norro** [ros-visualization/rqt_robot_monitor#25]
When trying the `rqt_robot_monitor` with ros2, I observe that the toplevel diagnostic status is not reflected in the coloring of the timeline at the bottom of the window. To reproduce do:

1. Install the [ros/diagnostics diagnostic_aggregator](https://github.com/ros/diagnostics/tree/ros2-devel) from ros2-devel branch
2. Execute the example, see https://github.com/ros/diagnostics/tree/ros2-devel/diagnostic_aggregator/example

With `ros2 topic echo /diagnostics_toplevel_state` you can see that the toplevel status indeed frequently changes between OK, warning, and error.

Expected:

- Toplevel status is reflected in the coloring of the timeline, i.e., timeline shows red, orange, and green parts

Actually:

- Timeline remains red no matter the diagnostics_toplevel_state

**Comment by fletzerm** [comment]
I have a similar problem with probably the same cause. When I double-click on a status message, the robot monitor crashes.
This is probably because the functions level_to_icon, level_to_color and level_to_text in the file util_robot_monitor expect an integer value, but the parameter passed is of type byte.
When I convert the passed variable to an Int, the robot monitor doesn't crash anymore and the color display of the timeline is correct.

**Comment by norro** [comment]
Oh, indeed, this is very plausible.

The root cause is probably that the diagnostic level [diagnostic_msgs/msg/DiagnosticStatus.msg ](https://github.com/ros2/common_interfaces/blob/master/diagnostic_msgs/msg/DiagnosticStatus.msg) is declared as `byte`. While `byte` was translated to `int8` in ROS 1, it is translated to `unsigned char` in ROS 2 now, though. I stumbled upon this with the diagnostic aggregator already, see: https://github.com/ros/diagnostics/issues/146

**Comment by arne48** [comment]
Great that you guys already found the root cause.
@fletzerm could you maybe wrap this up in a PR to the "ros2" branch?
This is also good opportunity to switch the devel branch from *-devel to ros2 as proposed by @norro

**Comment by fletzerm** [comment]
Following PR #26 should solve this issue. I have tested the changes and there should be no side effects.

**Comment by arne48** [comment]
#26 fixed this problem.
Updated packages will be published soon. 

Thanks to @fletzerm, @norro and @Karsten1987
