### ISSUE TITLE
Release into Melodic?

### ISSUE THREAD

**Issue by mark-goodall** [ros-visualization/rqt_robot_monitor#28]
It looks like there hasn't been a release into Melodic since #13 was fixed. Is it possible to release into Melodic?

**Comment by arne48** [comment]
Yes that is planned for melodic and noetic.
Currently I am still testing another patch to fix the timeline_view #27 .
Once this is stable the changes for both issues will be backported.

**Comment by arne48** [comment]
@mark-goodall sorry that it took so long.
It would be nice if you could verify #29 working, then I could prepare the release into Kame, Melodic and Noetic.
I always like to have at least one more person checking a release, besides me on my testing machines.

**Comment by arne48** [comment]
PRs for releases into all active distributions (Kinetic, Melodic, Noetic) were issued.
