### ISSUE TITLE
rqt_robot_monitor: Stale Diagnostics Not Shown in Error Pane

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_robot_monitor#3]
_From @DLu on November 23, 2016 20:3_

The [package description](https://github.com/ros-visualization/rqt_robot_plugins/blob/master/rqt_robot_monitor/package.xml#L9) mentions that stale or error diagnostics are grouped together. However, the current implementation [only looks for error or warn](https://github.com/ros-visualization/rqt_robot_plugins/blob/master/rqt_robot_monitor/src/rqt_robot_monitor/robot_monitor.py#L143)

This is easy enough to fix, but I wanted to discuss whether other people thought it was a bug first. 

_Copied from original issue: ros-visualization/rqt_robot_plugins#118_

**Comment by arne48** [comment]
For me a stale diagnostic provider is severe enough to be specially treated. 
I guess this will normally happen when a driver or controller dies so it should be added to the error pane as this is pretty bad and might need attention.
So I merged the small fix needed for this behavior.

**Comment by DLu** [comment]
:+1:
