### ISSUE TITLE
.gitignore?

### ISSUE THREAD

**Issue by paulerikf** [ros-visualization/rqt_robot_monitor#32]
Forgive me if this is a bit of a naive question, but is there a reason __pycache__ isn't .gitignored?

For reasons... I have `rqt_robot_monitor` (and the rest of foxy stuff)  built from source and added as submodules in a repository. It's somewhat annoying to always see `src/rqt_robot_monitor/__pycache__/` show up as "Untracked files" in the `rqt_robot_monitor` repo after building.

**Comment by arne48** [comment]
Well, most of the rqt plugin repositories have no .gitignore file.
I never thought about it that much as it seems that at least for these projects it doesn't bother me that much.
Now I have to merge the patch for #31 and I might consider to add a .gitignore file.
One point could be that besides the .git folder one doesn't want anymore hidden items.
Good point I will think about it.
