### ISSUE TITLE
How to embed RobotMonitorWidget in PyQt5

### ISSUE THREAD

**Issue by chrisflesher** [ros-visualization/rqt_robot_monitor#34]
I'm interested in embedding `RobotMonitorWidget` in my own application like this:
```
import rospy
import rqt_robot_monitor.robot_monitor
import sys
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QDialog
from PyQt5.QtWidgets import QVBoxLayout


class ControlPanel(QDialog):

    def __init__(self):
        QDialog.__init__(self)
        rospy.init_node('control_panel', anonymous=False)
        self.setWindowTitle('Control Panel')
        layout = QVBoxLayout()
        layout.addWidget(rqt_robot_monitor.robot_monitor.RobotMonitorWidget('', topic='diagnostics_agg'))
        self.setLayout(layout)
        self.show()


app = QApplication(sys.argv)
ex = ControlPanel()
sys.exit(app.exec_())
```

It seems to work somewhat but the status icons don't appear and I can't double click on a status to show the details. I was wondering if it is a good idea to attempt doing something like this or not? Any hints on the top of your head on how to resolve these issues would be appreciated!

**Comment by arne48** [comment]
Hi @chrisflesher,
based on the name you choose for your class I would assume you are trying to create a dashboard-like window with several nested widgets.
rqt allows you to have several widgets in one window and arrange them in a tiling-wm-like style.
It also supports perspectives so you can load a particular layout.
Maybe you can have  look at a tutorial like this and maybe this is already what you try to achieve: [https://www.clearpathrobotics.com/assets/guides/kinetic/ros/Creating%20RQT%20Dashboard.html](https://www.clearpathrobotics.com/assets/guides/kinetic/ros/Creating%20RQT%20Dashboard.html)

Best,

**Comment by chrisflesher** [comment]
Ok, thanks for the info. Will look into it.
