### ISSUE TITLE
4 instances of rqt_robot_monitor node are getting started while launching from launch file.

### ISSUE THREAD

**Issue by nrasulnrasul** [ros-visualization/rqt_robot_monitor#41]
I tried to launch `rqt_robot_monitor` from a launch file as below and I could see 4 instances of rqt_robot_monitor node. Where as launching the node from terminal launches one instance.

1) starting node from launch file:
```xml
<launch>
    <node pkg="rqt_robot_monitor" exec="rqt_robot_monitor" name="rqt_robot_monitor" output="screen" />
</launch>
```
2) starting node from terminal:
```sh
ros2 run rqt_robot_monitor rqt_robot_monitor
```

3) check the list of running nodes
```
ros2 node list
```

I am using ROS2 Humble on Ubuntu 22.04 and following are the installed ros-humble-rqt-robot-monitor details:

4)  package version details
```bash
dpkg -s ros-humble-rqt-robot-monitor
```
```bash
Package: ros-humble-rqt-robot-monitor
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 148
Maintainer: Aaron Blasdel <ablasdel@gmail.com>
Architecture: amd64
Version: 1.0.5-2jammy.20240125.224658
Depends: python3-rospkg-modules, ros-humble-diagnostic-msgs, ros-humble-python-qt-binding (>= 0.2.19), ros-humble-qt-gui, ros-humble-qt-gui-py-common, ros-humble-rclpy, ros-humble-rqt-gui, ros-humble-rqt-gui-py, ros-humble-rqt-py-common, ros-humble-ros-workspace
Description: rqt_robot_monitor displays diagnostics_agg topics messages that are published by diagnostic_aggregator.
 rqt_robot_monitor is a direct port to rqt of robot_monitor. All diagnostics are fall into one of three tree panes depending on the status of diagnostics (normal, warning, error/stale). Status are shown in trees to represent their hierarchy. Worse status dominates the higher level status. Ex. 'Computer' category has 3 sub devices. 2 are green but 1 is error. Then 'Computer' becomes error. You can look at the detail of each status by double-clicking the tree nodes. Currently re-usable API to other pkgs are not explicitly provided.
Homepage: http://wiki.ros.org/rqt_robot_monitor

```

**Comment by arne48** [comment]
@nrasulnrasul Thank you for submitting this issue.
I will have a look into it.
In the meantime can you check if this issue also occurs when using a python or yaml file to start the robot monitor?
And did you have similar issues with other rqt_plugins that you launched via a launch file?

**Comment by nrasulnrasul** [comment]
> In the meantime can you check if this issue also occurs when using a python or yaml file to start the robot monitor? 

Same behavior while launching from yaml or python launch files.

rqt.launch.yaml

```python

from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    node = Node(
            package='rqt_robot_monitor',
            namespace='',
            executable='rqt_robot_monitor',
            name='rqt_robot_monitor'
        )

    return LaunchDescription([
        node
    ])
```

rqt.launch.yaml
```yaml
launch:

- node:
    pkg: "rqt_robot_monitor"
    exec: "rqt_robot_monitor"
    name: "rqt_robot_monitor"
    namespace: ""
```
>And did you have similar issues with other rqt_plugins that you launched via a launch file?

No, I tried launching rqt_plot, rqt_action plugins from launch files. They start only one node.

------------------------------------------------------------------------------------------------------------------------------------------------------
Names of the nodes when 'rqt_robot_monitor' is started via "ros2 run ..." is different from when launched via launch file.

```bash
# node list when rqt_robot_monitor is launched via ros2 run
# ros2 run rqt_robot_monitor rqt_robot_monitor
ros2 node list 
/robot_monitor_log_node
/rqt_gui_py_node_289430
/timeline_log_node
/timeline_subscriber
```
```bash
# node list when rqt_robot_monitor is launched via launch files
ros2 node list 
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/rqt_robot_monitor
/rqt_robot_monitor
/rqt_robot_monitor
/rqt_robot_monitor
```

**Comment by arne48** [comment]
Thank you very much for the additional information @nrasulnrasul 
I found the root of the problem and currently testing the fixed version.

**Comment by arne48** [comment]
@nrasulnrasul 
I pushed my fix. Can you maybe try it out and give me feedback if it solves the problem? :)

**Comment by nrasulnrasul** [comment]
Your PR solved the issue, I could see only one node running.
