### ISSUE TITLE
New ROS2 release?

### ISSUE THREAD

**Issue by MCFurry** [ros-visualization/rqt_robot_monitor#44]
I just bumped into issue #41 which seems nicely solved in the [repo already](https://github.com/ros-visualization/rqt_robot_monitor/pull/43).
Unfortunately, there hasn't been a new release and thus this change didn't end up in the latest iron sync.
And so it seems, also won't make it into Jazzy?
Could you please do a new ROS2 release such that we can benefit from your improvements?

**Comment by arne48** [comment]
@MCFurry Thank you very much for your bump.
I will issue the releases tomorrow :)

**Comment by MCFurry** [comment]
Awesome! Thanks for the swift response!

**Comment by arne48** [comment]
New releases are issued: ([humble](https://github.com/ros/rosdistro/pull/41188)), ([iron](https://github.com/ros/rosdistro/pull/41189)), ([jazzy](https://github.com/ros/rosdistro/pull/41190)), ([rolling](https://github.com/ros/rosdistro/pull/41191))
Thanks again @MCFurry for the reminder
Hopefully they will be updated soon.

**Comment by MCFurry** [comment]
Cool! Thanks a lot!
